### ISSUE TITLE
Merging sanic_session into the core repo

### ISSUE THREAD

**Issue by subyraman** [huge-success/sanic#1196]
Hey there, I'm the "maintainer" of `sanic_session`; I put that in quotes because I haven't been doing a great job of maintaining it in the last few months. I wanted to get thoughts about merging the session handler into the core repo because it does seem that this is a big missing feature in sanic, does not have built-in session management, when most other frameworks do and I wouldn't want the functionality to start rotting because I don't have the time available to maintain it.

If not, maybe ownership could be transferred over to people on the core team who feel they are up to maintaining it.

If that's fine, I can start building out a pull request to merge in the functionality.

**Comment by ahopkins** [comment]
My personal thoughts is that it is not necessary to be a core feature. I honestly hope you do not take my comment poorly, looks like you added a great (missing) feature, but I like that Sanic is barebones.

Personally, I'm using sanic to power stateless microservices, so session management is unnecessary for me. What was necessary was a way to manage authentication across my services using JWTs, which is why I created [sanic-jwt](https://github.com/ahopkins/sanic-jwt).

With that said, session management I agree is an important feature... and for sanic to be a successful project, a package like yours needs to be well maintained. So if the answer is merge or drop, well for the sake of the community and longevity of the project I'd be in favor of merging. However, in general, I like the batteries not included approach so that I can pick and choose from a buffet and build the app I want. I cannot tell you how many django apps I've built in the past, completely disregarding the forms API.

**Comment by xen** [comment]
I also agree with Adam. The session is a nice feature but is not necessary for every project. Microframework approach that follows Sanic already proved its success. Sanic should not be like a Django. For example, Flask-sessions is a separate library. Also, ability to save state require having bindings to storages and require to maintain dependencies. That also means to advertise some preferences for the developers and limit other options. 

But the same time I agree that `sanic_session` is important for the community and definitely can be under the umbrella of the other developers. I don't know if there are any plans to create some foundations for the Sanic development. But if yes I vote to include to the supported list.

@subyraman I'm trying to reach you for some amount of time regarding `sanic-session`, you don't have any public emails and you are don't answer to my mentions in Github issues. I wish to have merged my PR to the package and offer to help with support of the package. Add me to the contributors' list or give some response.

**Comment by subyraman** [comment]
@xen Feel free to message me on Twitter and I can get you the correct permissions. https://twitter.com/subyraman

**Comment by xen** [comment]
@subyraman Thank you. Sent you a message over Twitter.
