### ISSUE TITLE
Should modify Blueprint's default url_prefix to empty string?

### ISSUE THREAD

**Issue by chenjr0719** [huge-success/sanic#1325]
The current default value of `url_prefix` is `None`(check [here](https://github.com/huge-success/sanic/blob/30e6a310f132752669a74927530e8bc52a51e98e/sanic/blueprints.py#L18)). This will raise an `TypeError: must be str, not NoneType` if use this default value with `Blueprint.group()` because of [line 57](https://github.com/huge-success/sanic/blob/30e6a310f132752669a74927530e8bc52a51e98e/sanic/blueprints.py#L57) in `blueprints.py`.

Considering to modify the default value from `None` to `''` or add an if statement before line 57.

**Comment by ahopkins** [comment]
Adding an `if` statement would likely to have less of an impact on compatibility issues.

**Comment by chenjr0719** [comment]
I send a PR #1334 to fix this issue and use `os.path.normpath` to avoid `url_prefix` become invalid format like `/api//v1`.
You can also check the test which I added in PR #1334,  it explains why I encounter this issue.
Should I just close this issue now?

**Comment by vltr** [comment]
@chenjr0719 using `os.path` wouldn't break this under Windows?

@sjsadowski @yunstanford I think we should add AppVeyor to our CI list if we are going to support Windows. What's your thoughts?

**Comment by sjsadowski** [comment]
@vltr I think that supporting windows requires a larger group discussion. Previously the maintainers have included many patches for windows compat - like excepting uvloop and ujson from windows installs - so it seems like it's a passive goal. 

I'm fine with making it an active goal, and appveyor does provide free hosting for OSS projects. I'm not sure I want to do it for the 18.12 release though.

**Comment by chenjr0719** [comment]
@vltr well, it really breaks on windows. How about use `pathlib.Path('/api//v1').as_posix()` to deal the compatibility problem? This can also work nicely on Linux and Windows.

**Comment by vltr** [comment]
> @vltr I think that supporting windows requires a larger group discussion.

@sjsadowski that is completely understandable. I _thought_ that Windows was a goal for Sanic (blame me), mostly for some comments regarding being able to install it under Windows with the 0.8.x version, along with [some of the code](https://github.com/huge-success/sanic/blob/master/setup.py#L54) inside `setup.py` (or perhaps lack of it, such as the `Operating System` classifier). I think this could be set for a later discussion as well.

> @vltr well, it really breaks on windows. How about use `pathlib.Path('/api//v1').as_posix()` to deal the compatibility problem? This can also work nicely on Linux and Windows.

@chenjr0719 I think that would work, but I really do not like using modules that are meant for use with the filesystem to perform URL normalization since there are a lot of small differences and rules regarding them, such as removing trailing slashes (`pathlib.Path('/api//v1/').as_posix() == "/api/v1"`). Also, collapsing multiple slashes does not seems to be strictly necessary since [I can add a lot of them and end up in the same place](https://github.com/huge-success/////sanic/////issues/////1325#issuecomment-426153264).

Now, if this is only to avoid multiple slashes to the Blueprint (that I think it's what you're trying to achieve), why not leave a simple replacement regex `re.sub(r'\/{2,}', "/", "/api//v1")` ?

```python
re.sub(r'\/{2,}', "/", "/api//v1") == "/api/v1"
re.sub(r'\/{2,}', "/", "/api//v1//abra//cadabra") == "/api/v1/abra/cadabra"
re.sub(r'\/{2,}', "/", "/api//v1//abra//////cadabra") == "/api/v1/abra/cadabra"
```

I really don't know what would be the best approach, but I think a simple regex may suffice if the only problem is the multiple slashes ... But I'll leave this up to you :wink:

**Comment by sjsadowski** [comment]
@vltr To be fair, sanic is still very "run at your own risk" - however if we officially state that we want windows to be supported, we should be running all our tests in a windows environment in addition to all of them currently running on trusty. I guess we should also look at updating the test platform to use or include bionic...

**Comment by vltr** [comment]
> To be fair, sanic is still very "run at your own risk"

@sjsadowski , I couldn't agree on that more :wink:
Anyway, we can add these platforms, perform more CI scripts and tests in other platforms as well ... IDK, this should be a team discussion perhaps (for future releases or LTS already)?

**Comment by vltr** [comment]
@sjsadowski yeap, this gives a year long work of "code hammering" to make Sanic work even in a Raspberry Pi :sweat_smile:

**Comment by chenjr0719** [comment]
@vltr In my use case, the multiple slashes is the only case that will cause problems, use `re.sub` can achieve my goal and it's better than other options also without side effects. huge grateful for your suggestion.

Here is an example to explain why multiple slashes should be avoided in `Sanic`, the `url_prefix` of `Blueprint` and `Blueprint.group()` are the most possible places where can cause this issue, so I'm trying to prevent this in `Blueprint.group()`.
```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.get('/api////v1/route////test///')
def route_test(request):
    return text('accessed')

req, resp = app.test_client.get('/api/v1/route/test')
```

The logs:
```
[2018-10-03 10:18:24 +0800] [23328] [INFO] Goin' Fast @ http://127.0.0.1:42101
[2018-10-03 10:18:24 +0800] [23328] [INFO] http://127.0.0.1:42101/api/v1/route/test/
[2018-10-03 10:18:24 +0800] [23328] [ERROR] Traceback (most recent call last):
  File "/home/jacob/Workspace/Codes/GitHub/sanic/sanic/app.py", line 592, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/jacob/Workspace/Codes/GitHub/sanic/sanic/router.py", line 359, in get
    return self._get(request.path, request.method, '')
  File "/home/jacob/Workspace/Codes/GitHub/sanic/sanic/router.py", line 419, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /api/v1/route/test/ not found

[2018-10-03 10:18:24 +0800] - (sanic.access)[INFO][127.0.0.1:53460]: GET http://127.0.0.1:42101/api/v1/route/test/  404 50
[2018-10-03 10:18:24 +0800] [23328] [INFO] Starting worker [23328]
[2018-10-03 10:18:24 +0800] [23328] [INFO] Stopping worker [23328]
[2018-10-03 10:18:24 +0800] [23328] [INFO] Server Stopped
```

BTW, I'm already run `Sanic` on Raspberry Pi with ubuntu mate in past year. There are no any complicated works needed, just `pip install sanic` and it can works. I think support Windows will be more difficult than support Raspberry Pi.

**Comment by vltr** [comment]
@chenjr0719 I'm glad that the regex solves this issue.

```python
@app.get('/api////v1/route////test///')
```

I think this might (not to mention "should") be avoidable by the developer :smile:
The example I gave regarding multiple slashes is that a lot of reverse proxy servers and even web frameworks already deals with that on parsing. I should _guess_ this is not the case with Sanic and, in case this is an issue, I think a new one should be created because that's up for the internal router.

@sjsadowski @yunstanford what do you think? I also guess that the Sanic router might not handle collapsing (`/../`) as well.

> BTW, I'm already run `Sanic` on Raspberry Pi with ubuntu mate in past year.

Yeah, I guess Sanic pretty much works with Linux on any platform (I'm being very generalist here). I was just joking on having a CI running on peculiar machine specifications such as the Raspberry Pi, what an overkill :sweat_smile:

**Comment by chenjr0719** [comment]
Since the PR is merged, close this issue.
