### ISSUE TITLE
Test case:[test_keep_alive_timeout.py] In the file,  a new TCP connection was not created after the  'keep alive timeout'

### ISSUE THREAD

**Issue by luochenxi** [huge-success/sanic#1426]
@hramezani Hi，Test case:[test_keep_alive_timeout.py](https://github.com/huge-success/sanic/blob/master/tests/test_keep_alive_timeout.py)  In the file, "test_keep_alive_client_timeout() "  and  "test_keep_alive_server_timeout()" 
Method ， a new TCP connection was not created after the  'keep alive timeout'.
Or is it where I understand it wrong?

* warnings: (See the green box section, please!)
![image](https://user-images.githubusercontent.com/18586097/49794300-37426f80-fd72-11e8-97fa-6d4fd24834c6.png)

**Code snippet**
Related code, please see [test_keep_alive_timeout.py](https://github.com/huge-success/sanic/blob/master/tests/test_keep_alive_timeout.py)

**Expected behavior**
Call "test_keep_alive_client_timeout() "  and  "test_keep_alive_server_timeout()" 
Method , a new TCP connection was created after the 'keep alive timeout'

**Environment:**
 - OS: macOS 10.13
 - Version :  sanic==0.8.3, aiohttp==3.4.4

**Comment by hramezani** [comment]
Hi @luochenxi, I just fix the lint problem for this file. unfortunately, I have no idea about your question.

**Comment by luochenxi** [comment]
> 嗨@luochenxi，我只修复了这个文件的lint问题。不幸的是，我不知道你的问题。

Ok, Thanks!

**Comment by luochenxi** [comment]
@ashleysommer @yunstanford  Hi，Can you help me with this question?

**Comment by chenjr0719** [comment]
@luochenxi 

Here is my understanding of [test_keep_alive_timeout.py](https://github.com/huge-success/sanic/blob/master/tests/test_keep_alive_timeout.py)(if something wrong, just blame me):

To verify server side and client side will **not** create a new TCP connection, the `ReuseableTCPConnector()` use an attribute `old_proto` to store the protocol of the first request. Once the second request is created, `ReuseableTCPConnector` will compare `old_proto` with protocol of new request. And, if it is not the same protocol, `ReuseableTCPConnector` will raise an exception(see L22-L24).

https://github.com/huge-success/sanic/blob/4efd450b324c3e379eed4e8e6ae075e972917400/tests/test_keep_alive_timeout.py#L18-L27


So, does `test_keep_alive_client_timeout()` and `test_keep_alive_server_timeout()` create new TCP connection?

My answer is **yes**, they both create a new TCP connection. These two test cases actually catch an exception raised by `ReuseableTCPConnector.connect()`. This means the first request and the second request comes from different TCP connections and the `old_proto` is different from `new_conn._protocol`.

And, about those warnings, it caused by the test case `test_keep_alive_server_timeout()`. In this case, the server side closes the connection first. This made the `aiohttp.client`(used by client side) throw some warnings.

**Comment by luochenxi** [comment]
@chenjr0719  Good！ Thanks for your guidance。
