### ISSUE TITLE
when I set ,the parameter workers=2 or bigger ,the  sanic  not work,why????

### ISSUE THREAD

**Issue by lingdavid** [huge-success/sanic#1461]
`from sanic import Sanic
from sanic.response import text,json

from DCNN_RequestHandler import DCNN_RequestHandler

rHandler = DCNN_RequestHandler()
app = Sanic(__name__)
@app.route('/classify', methods=['GET', 'POST'])
async def input(request):
    sentence = request.args.get('text')
    if sentence:
        resultDict = rHandler.getBatchResults(sentence)

        label = resultDict['result']
        question_label = label
        question_pro = resultDict['score']
      
        json_str = json({'label': question_label, 'score': str(question_pro)})
        return json_str
    else:
        return "please input text!!!"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=10017, debug=False, workers=2)`

when I set workers >1,  the program getting hanged  (if I set workers=1,it is nomal)，why?

**Comment by vltr** [comment]
Hello, @lingdavid !

Would you mind give us some more information regarding your Python version, OS, testing environment and etc? Thanks!

**Comment by vltr** [comment]
Some stack trace (if available) would be welcome as well, any information regarding your issue :smiley:

**Comment by lingdavid** [comment]
python 3.6.5 , linux（ubuntu 3.19.0），tensorflow1.2.0,   sanic0.8.3

**Comment by lingdavid** [comment]
ubuntu 3.19.0 ,python 3.6.5,  tensorflow 1.2.0 , sanic 0.8.3

**Comment by vltr** [comment]
Ok, can you provide the full stack trace when you try to run your Sanic app using `2` workers?

**Comment by lingdavid** [comment]
The program did not report an error, But the page is not responding.

`[2019-01-07 17:55:28 +0800] [23340] [INFO] Goin' Fast @ http://0.0.0.0:10017
[2019-01-07 17:55:28 +0800] [23464] [INFO] Starting worker [23464]
[2019-01-07 17:55:28 +0800] [23465] [INFO] Starting worker [23465]`

22589 pts/20   Sl     0:25 python -u DCNN_server.py
22755 pts/20   S      0:00 python -u DCNN_server.py
22756 pts/20   S      0:00 python -u DCNN_server.py

**Comment by lingdavid** [comment]
When the program runs, it does can receives a request, but gets stuck in the function which I defined(but when workers=1,it is normal), and then does not return normally.

**Comment by vltr** [comment]
Ok, since you're using `tensorflow` as well under the hood, we need to check _if_ `tensorflow` works when [spawning multiple processes](https://github.com/huge-success/sanic/blob/96af1fe7cff06fd9273e77e23027711fb028cd65/sanic/server.py#L825-L869) (something **Sanic does not do** with only one worker) using the [`multiprocessing`](https://docs.python.org/3.6/library/multiprocessing.html) module. To test your environment, try this simple script:

```python
import os
from sanic import Sanic
from sanic.response import text

app = Sanic()


@app.route("/")
async def test(request):
    return text(str(os.getpid()))


def main():
    app.run(workers=4)


if __name__ == "__main__":
    main()
```

Run in your terminal:
```
$ python test-sanic-os-pid.py 
[2019-01-07 08:09:31 -0200] [28877] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2019-01-07 08:09:31 -0200] [28920] [INFO] Starting worker [28920]
[2019-01-07 08:09:31 -0200] [28919] [INFO] Starting worker [28919]
[2019-01-07 08:09:31 -0200] [28921] [INFO] Starting worker [28921]
[2019-01-07 08:09:31 -0200] [28922] [INFO] Starting worker [28922]
```

And check if it works and returns different PIDs:

```
$ curl http://127.0.0.1:8000/
28922

$ curl http://127.0.0.1:8000/
28921

$ curl http://127.0.0.1:8000/
28920

$ curl http://127.0.0.1:8000/
28919

$ curl http://127.0.0.1:8000/
28921

$ curl http://127.0.0.1:8000/
28921
```

If this works in your machine as it is supposed to, then you'll need to check if `tensorflow` (that just have a Python interface) supports `multiprocessing`. If it does not _and_ you still want to leverage your computer cores, you can spawn multiple Sanic processes and use a load balancer to reach them out :wink:

Some related links for `tensorflow` and `multiprocessing`:
- [tensorflow-and-multiprocessing-passing-sessions @ SO](https://stackoverflow.com/questions/36610290/tensorflow-and-multiprocessing-passing-sessions)
- [Session hang issue with python multiprocessing @ GH](https://github.com/tensorflow/tensorflow/issues/8220)

**Comment by lingdavid** [comment]
It works. The output is the same as you.
I will check  the tensorflow ,thanks!

**Comment by vltr** [comment]
Great, thanks @lingdavid ! If you need further help, let's us know here or for more comprehensive ideas and discussions, you can check out our [community forums](https://community.sanicframework.org/) as well! :wink:
