### ISSUE TITLE
How to use WebSocket in a event-based design?

### ISSUE THREAD

**Issue by mojimi** [huge-success/sanic#1493]
I don't understand how to use the WebSocket in a event-driven design, the examples use a while true loop which I'm having a hard time to adapt to my context.

First, how does the WebSocket works? Is the route function for the WebSocket only run once? That's why it needs a loop? Does the connection closes when this function is returned?

How can I make this loop wait for a CPU-bound blocking executor task without blocking other requests for example?

Mockup example of what I'm trying to achieve :

```python
@app.websocket('/pdf')
async def pdf(request, ws):
  r = request.json
  id = uuid4().hex
  taskPath = await createProcessingTask(id)
  pdfsBytes = await asyncio.get_running_loop().run_in_executor(None, syncRenderPdfs, taskPath, r)
  await ws.send(pdfsBytes)
```

**Comment by greentornado** [comment]
I have the same question, too

**Comment by sjsadowski** [comment]
I'm a bit confused as to your question here; websockets in general are a stateful, bi-directional protocol so you wouldn't just open a websocket connection, have the server send data, and close it. There's no need, since there's no further change. 

Could you describe what you're trying to accomplish?

From my POV: it looks like you're trying to stream a binary file (pdf) over a websocket... which is fine if a bit confusing, but not really a great use case for websockets.

**Comment by mojimi** [comment]
@sjsadowski It's because the PDF might take too long, using a "regular" connection has caused timeouts in peaks.

The problem is the might, I need to be sure so the file doesn't get lost.

There's also polling, but I was recommended to try websockets.

**Comment by sjsadowski** [comment]
I guess I could understand, but websockets are generally for bi-directional communication. I think you probably still need a stream, just like was recommended for your excel file in #1485

**Comment by mojimi** [comment]
> 
> 
> I guess I could understand, but websockets are generally for bi-directional communication. I think you probably still need a stream, just like was recommended for your excel file in #1485

Sure, but would a stream solve a connection timeout error? Can I stream inside a websocket?

I'm just trying to make the less amount of requests possible, having the client wait for the file to be generated isn't working (browser timeouts) and polling isn't ideal, so the solution has to be websockets

**Comment by sjsadowski** [comment]
@mojimi it should if you're using the connection keep-alive header, which may be what you need for your regular long-running response too.

> If file is taking too long, client can send a message to the server that he wants to be emailed instead and leave the browser

Ok, but that has to be handled on the browser side, and it's still not a great use-case for websockets.

Let me summarize from my point of view:
It sounds like you are generating a binary file on demand, and then that file needs to be sent to the requestor. Right now, however you are doing that is causing the initial request to timeout, and you are looking for a solution to make sure that doesn't happen. You do not want to poll for completion in the background, but instead want to make sure the connection stays open long enough to deliver the entire file to the requestor, or alternately if the requestor wants to opt out, to give them the option to have the file delivered in an alternate way, specifically email.

Is that correct?

**Comment by mojimi** [comment]
> 
> 
> @mojimi it should if you're using the connection keep-alive header, which may be what you need for your regular long-running response too.
> 
> > If file is taking too long, client can send a message to the server that he wants to be emailed instead and leave the browser
> 
> Ok, but that has to be handled on the browser side, and it's still not a great use-case for websockets.
> 
> Let me summarize from my point of view:
> It sounds like you are generating a binary file on demand, and then that file needs to be sent to the requestor. Right now, however you are doing that is causing the initial request to timeout, and you are looking for a solution to make sure that doesn't happen. You do not want to poll for completion in the background, but instead want to make sure the connection stays open long enough to deliver the entire file to the requestor, or alternately if the requestor wants to opt out, to give them the option to have the file delivered in an alternate way, specifically email.
> 
> Is that correct?

Yes, that would be the ideal scenario i'm theorizing.

I want the client to be able to say "I give up waiting", so that would require a two-way connection right?

I didn't know about the keep-alive, does that have a persistent behavior cross-browser? My main concern is that a generated file doesn't get in the "limbo" because something happened on the client side.

**Comment by sjsadowski** [comment]
> I didn't know about the keep-alive, does that have a persistent behavior cross-browser?

Yes. It is implemented slightly differently in different engines, but all major browsers support `Connection: keep-alive` headers. There are other options, too, for setting specific timeouts and what not. Just do a web search for those

So if it were me, I would use a standard request to have the file delivered, which I would do with an asynchronous javascript request, leaving you free to provide some sort of UX indicator that the file was in progress, and that also would allow you to mask that as being repetitive polling tasks rather than a single task that the browser (and client) are waiting on.

Polling makes it a bit easier because once the file is completely generated, you can actually fire a redirect to the browser to take them to the generated file.

That could mean, too, that you can have a task queue that is triggered if the requester tells you (through click or other interaction) that they don't want to wait for the file, and the requests in that queue could send an email.

It would be a lot easier to whiteboard this out, but to me it sounds like the user experience is of primary importance to you, so long as the technical portion (the file generation) is completed, and I would levy browsers javascript capabilities to make that happen.

**Comment by mojimi** [comment]
@sjsadowski Yes that's mostly what I'm doing already, except I haven't tested if keep-alive will give timeouts.

But you do see how that would be simpler with a websocket right?

Your and my current solution requires 3 routes (getPdf, pollTask, editTask(email)) and possibly several requests due to polling.

Also I might be wrong but there is a atomicity issue with the user editing a task in the queue to be sent by email.

It could all be solved with one single websocket connection, but it would require a class-like implementation of WebSocket instead of a loop-like (that's the way I see it atleast)

One middle-ground would be to have the polling endpoint be a websocket, that could be interesting.

**Comment by sjsadowski** [comment]
Well it's actually bad, because the browser side now has to handle multiple types of data, so you'll be parsing what's being delivered from the websocket, unless you have multiple websocket connections. I get where you're trying to reduce the general complexity for the user. So that complexity is reduced on the backend, but increased for the browser side of things, where you may need to parse multiple kinds of data in the browser.

> Also I might be wrong but there is a atomicity issue with the user editing a task in the queue to be sent by email.

You're probably not wrong about that, but in my case if a user indicated that they didn't want to wait, I would cancel the existing task and insert a new email delivery task into the queue. At that point, the user has already effectively given up on waiting, so you don't really lose much from the user experience by generating the file all over again.

Also you might want to come over to the [community](https://community.sanicframework.org/) and ask there, it's pretty good for helping with theoreticals and best-path type scenarios such as yours.

**Comment by vltr** [comment]
@mojimi what you need is a simple call that spawns any worker to create whatever you need, close the connection (while running in background, Idk, Celery, thread, aiomultiprocess, take a pick) and then warn your client when this operation is complete (using websockets, SSE, again, take a pick). Am I correct?

**Comment by mojimi** [comment]
> 
> 
> @mojimi what you need is a simple call that spawns any worker to create whatever you need, close the connection (while running in background, Idk, Celery, thread, aiomultiprocess, take a pick) and then warn your client when this operation is complete (using websockets, SSE, again, take a pick). Am I correct?

Exactly, I was theorizing the most ideal scenario to do this while using less amount of requests possible, and guaranteeing that the worker's work is not lost

**Comment by vltr** [comment]
@mojimi then it's all to your own implementation. All you need is to "signal" the start of the background task and then receive any callback and show it to the user. I'll not go into specifics because there's a bazillion ways this can be accomplished :wink:

**Comment by Yensan** [comment]
this is an interesting question. I had encountered the same type of assignment. 
User send request(a task) ----- backend need a period to finish the task ---- when it finished, notify the user ----- User get the result.
I used celery as task queue in back-end,  started loop request at some point  in fore-end. This is a yuck implementation, I know. But how to use websockets notify  users?

**Comment by ahopkins** [comment]
Definitely no need for long polling here. You really have a couple options:

- Push off to a celery process and have celery trigger a response back over the same websocket when it is done (I have something similar to this operational on a project I am working on)
- Push off to an `asyncio.Queue` ins something similar to this: https://community.sanicframework.org/t/how-to-use-asyncio-queues-in-sanic/166/4?u=ahopkins
- Push off to a pub/sub and create a celery like task manager that listens to the pubsub channel and responds back to it

In all the scenarios you need to have a couple of components in your websocket: a consumer and a producer. [Here is a great overview](https://websockets.readthedocs.io/en/stable/intro.html#common-patterns) of how you could accomplish this. 

I also highly suggest you take a look at some Python Redis packages to learn about using it as a pubsub: [`redis`](https://github.com/andymccurdy/redis-py#publish--subscribe), [`aredis`](https://github.com/NoneGG/aredis/blob/master/examples/pubsub.py), [`aioredis`](https://aioredis.readthedocs.io/en/v1.2.0/mpsc.html)
