### ISSUE TITLE
Serving Create-React-App, WildCard and Exceptions

### ISSUE THREAD

**Issue by episodeyang** [huge-success/sanic#1543]
Moved from comments in #1126 

I'm running into this problem: when I do `GET localhost:3002/profiles`, I thought the async handler is supposed to catch this via the `/<path:path>` route, with `path="profiles"`. However the server errors out with "file not found", apparently from the static handler.

```python
import os
from sanic import Sanic
from sanic.response import file

# gets current directory
BASE = os.path.realpath(__file__)
print(BASE)
print(os.path.dirname(BASE))

build_path = os.path.join(os.path.dirname(BASE), "../app-build")
print(build_path)

app = Sanic()
# serve js file for webpack
app.static('/', build_path)


# app.static('/main.js', './app-build/main.js', name='main.js')

@app.route('/')
@app.route('/<path:path>')
async def index(request, path=""):
    print('hey ====', [path])
    return await file(build_path + '/index.html')


if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=int(os.environ.get('PORT', 3002)),
        workers=int(os.environ.get('WEB_CONCURRENCY', 1)),
        debug=bool(os.environ.get('DEBUG', '')))
```

I would like to know the precedence in the route handling above.

### My expectation

I was expecting that the static handler would take precedence, and when it fails to find the file, it delegates the serving need under the same prefix to the async handler. This is how it works with express (afaik), but I can see why it doesn't work this way.

I am planning on handling this using app-level exception handling instead, but would like to know a clean and officially supported way for this case when the static file path and the root html serving path overlap.

**Note:** this is a common use case with CRApps w/ client-side routing

https://github.com/huge-success/sanic/issues/998#issuecomment-344454835

Here is my final solution--it is a bit ugly and unclean:

```python
import os
from sanic import Sanic
from sanic.exceptions import FileNotFound
from sanic.response import file

# gets current directory
BASE = os.path.realpath(__file__)
print(BASE)
print(os.path.dirname(BASE))

build_path = os.path.join(os.path.dirname(BASE), "../app-build")
print(build_path)

app = Sanic()
# serve js file for webpack
app.static('/', build_path)


# app.static('/main.js', './app-build/main.js', name='main.js')

@app.route('/')
@app.exception(FileNotFound)
async def index(request, exception=None):
    print('hey ====', [exception])
    return await file(build_path + '/index.html')


if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=int(os.environ.get('PORT', 3002)),
        workers=int(os.environ.get('WEB_CONCURRENCY', 1)),
        debug=bool(os.environ.get('DEBUG', '')))
```

**Comment by madelyneriksen** [comment]
Hey, firstly sorry: this is not a direct answer to your question. Rather, at work I use React + Reach/Router + Sanic for a service and getting the development environment up and running was trickier compared to a quick catch-all like in other frameworks (looking at you Django).

I ended up creating the development environment using `docker-compose` to run an nginx server, acting as a reverse proxy for Sanic but _also_ mounting the html file, bundled JS, etc. and serving it. You can just use a docker volume and mount the host path containing the files. Quick example:

```yaml
# docker-compose.yml
version: '3'
services:
  web:
    image: nginx
    volumes:
      - "./static:/usr/share/nginx/html"
      # You'll need an nginx configuration that handles proper routing of requests.
      - "./conf/nginx.conf:/etc/conf/nginx.conf"
    ports:
      - "8080:80"
  sanic:
     # Your sanic container for nginx to route requests to.
     # (ex. route requests to /api to sanic)
     ...
```

You don't _have_ to use docker of course. Any `nginx` server, in a VM, container, or on the host, should be fine. Depending on how your build system does hot reloading, it might even be supported out of the box.

**Non-CORS Safe Alternative**

You can _also_ just have two development servers running when working on your project, and change out the urls at build time using environment variables or whatever. The issue is that some browsers will block JS requests to another domain because of CORS, and changing that for different JS development servers ranges from supported to not at all supported.

However, if this is a solution that works for you and your setup, I'd probably go with it, because it's more straightforward than messing around with `nginx` and containers.

**Comment by noa14642** [comment]
ماهاذا بحق الجحيم لم افهم شيء

**Comment by sjsadowski** [comment]
Hi there - the sanic community primarily communicates in English. Would you mind posting an English translation for your comment, please?

Sent from my mobile device; please excuse my brevity

________________________________

**Comment by episodeyang** [comment]
it seems to mean “what the fucking hell”

**Comment by LewisGaul** [comment]
I'm seeing the same issue, I can't get the `/<var>` route handling to work, and the workaround hack of catching the 'FileNotFound' exception is what I've had to fall back on. Is there an issue here? I've seen this on Sanic 19.3.1 and 20.6.3.

**Comment by ahopkins** [comment]
> I'm seeing the same issue, I can't get the `/<var>` route handling to work, and the workaround hack of catching the 'FileNotFound' exception is what I've had to fall back on. Is there an issue here? I've seen this on Sanic 19.3.1 and 20.6.3.

Can you post over at the community forums and include some code snippets for what you are trying to do?

**Comment by LewisGaul** [comment]
For the benefit of anyone coming up against this (@geyang), the discussion I posted is at https://community.sanicframework.org/t/unexpected-dependency-of-ordering-with-static-dir-and-dynamic-routes/632.

The conclusion was: the correct way to solve the OP's problem is to have `app.static('/', build_path)` come *after* the route declaration, so that it serves as a fallback rather than a catch-all.

As per the linked discussion - it would be nice from a user's perspective if the ordering made no difference. However, fixing that is considered an enhancement, and is unlikely to be tackled any time soon due to the amount of rewrite that would be required to fix it properly.
