### ISSUE TITLE
build time increased a lot

### ISSUE THREAD

**Issue by yunstanford** [huge-success/sanic#1569]
https://travis-ci.org/huge-success/sanic/builds
looks like build time increased a lot, after merging https://github.com/huge-success/sanic/pull/1562

cc: @huge-success/sanic-core-devs @ahopkins

**Comment by ketan86** [comment]
@yunstanford Agree, almost three times the previous build of #1562.  This needs some investigation if build time increase like this is not expected.

**Comment by ahopkins** [comment]
This is indeed bizarre. The difference in the build is that we are replacing `aiohttp` for `requests_async`. The only other change that impacted the build was renaming `pyproject.toml` since we are only using it for building `black` right now and not as in relation to [PEP 518](https://www.python.org/dev/peps/pep-0518/).

The reason I did that was because the builds [started conflicting with the `toml` file](https://travis-ci.org/huge-success/sanic/jobs/525713352#L514):

>>> ERROR: Error installing 'file:///home/travis/build/huge-success/sanic': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

**Comment by ahopkins** [comment]
Just read @yunstanford PR linked above to `httpcore` (a dependency of `requests-async`, and potentially [a new dependency of `requests` as well](https://www.kennethreitz.org/essays/requests3-update))
