### ISSUE TITLE
After the websocket is started, the remaining api interfaces cannot be accessed.

### ISSUE THREAD

**Issue by FishEatingCat** [huge-success/sanic#1578]
After the websocket starts, I can't access other APIs, they are in the same file.
Codes
other api
```
@api.post('/service')
async def add_service(request):
    return ase.add_new_service(request)
```
websocket
```
@api.websocket('/devices/updates')
async def feed(request, ws):
    # logger.debug("in websocket")
    ctx = zmq.Context()
    subscriber = ctx.socket(zmq.SUB)
    subscriber.connect("ipc:///tmp/sentry")
    subscriber.setsockopt(zmq.SUBSCRIBE, b"")
    while True:
        try:
            msg = subscriber.recv_json()
            await ws.send(msg)
            await asyncio.sleep(0)
        except ConnectionError:
            ws.ConnectionClosed()
```
This is the debug information after the websocket connection is successful.
![image](https://user-images.githubusercontent.com/40785341/57830105-a3bf1000-77e3-11e9-9a27-7d6a6e95c301.png)

What should I do to continue to access other apis after the websocket connection is successful?

**Comment by chenjr0719** [comment]
How many workers did you use? If you only use one worker, after connect to the WebSocket endpoint, your worker will be occupied until the WebSocket connection closed.
You can use `app.run(workers=4)` to increase the numbers of workers.

**Comment by ahopkins** [comment]
@chenjr0719 That is not entirely true. It will somewhat depend upon how your app is setup. And while I think your answer is correct, it is missing one thing that I would like to add.

Take this barebones example:

```python
from sanic import Sanic, response
from datetime import datetime

app = Sanic(__name__)


@app.get("/")
async def endpoint(request):
    now = datetime.utcnow().strftime("%c")
    msg = f"[{now}] Foobar"
    return response.text(msg)


@app.websocket("/feed")
async def feed(request, ws):
    data = "hello!"
    await ws.send(data)
    while True:
        now = datetime.utcnow().strftime("%c")
        data = await ws.recv()
        msg = f"[{now}] Received: {data}"
        await ws.send(msg)


if __name__ == "__main__":
    app.run(debug=True)
```

I can open a socket, and then ping my server from HTTP without closing the socket. This works because all of my blocking calls here (`ws.recv` and `ws.send`) are asynchronous. While I am waiting for a message to arrive, I am yielding back to the server, which is able to accept an incoming request.

---

The problem that I see in the example by @FishEatingCat is that `subscriber.recv_json()` looks to be blocking. So, when that function executes, the whole app locks up there until a response arrives.

Let's take the above example and make a change:

```python
@app.websocket("/feed")
async def feed(request, ws):
    data = "hello!"
    await ws.send(data)
    while True:
        for i in range(10):
            time.sleep(1)
            print(f"Sleeping: {10-i}")
        now = datetime.utcnow().strftime("%c")
        data = await ws.recv()
        msg = f"[{now}] Received: {data}"
        await ws.send(msg)
```

Now, when a websocket connects, there is 10 seconds where **nothing** can happen. If you hit the HTTP endpoint, it will not receive a response until **after** the 10 seconds.

This is sort of like what is happening with: `msg = subscriber.recv_json()`

---

So, in this case, adding workers *would* help, but I am not sure it really does in the long run. Depending upon the use case that is. I could add more workers to my above example and that would allow both my websocket to stall for 10 seconds, and my HTTP endpoint to continue to function. But, what happens if I get more websocket connections?

I think the answer for @FishEatingCat is one of two options: 

1. find an async enabled package to connect to `subscriber.connect("ipc:///tmp/sentry")`; or
1. use another alternative method for concurrency (threading or multiprocessing).

Closing for now, please feel free to continue the conversation.

**Comment by FishEatingCat** [comment]
> How many workers did you use? If you only use one worker, after connect to the WebSocket endpoint, your worker will be occupied until the WebSocket connection closed.
> You can use `app.run(workers=4)` to increase the numbers of workers.

The default number of workers used. Is websocket asynchronous? When await, why not go out and perform other tasks? I am new for this.

I tried increasing the number of workers and it really solved the problem I mentioned above.

**Comment by FishEatingCat** [comment]
I will try @ahopkins ‘s method of 

> find an async enabled package to connect to subscriber.connect("ipc:///tmp/sentry");

**Comment by ahopkins** [comment]
> Is sanic websocket asynchronous? 

Yes.

> When await, why not go out and perform other tasks? I am new for this.

When the `async` coroutine executes, everything runs synchronously until it gets to an `await`. Then, more or less, it goes back to the loop to check if there are other things to do. So, any code that does not have an `await` will block your loop from doing anything else. For many things this is fine. But, especially when talking about web services, code that needs to make a network call to some other service (whether it be Postgres, another HTTP server, or anything else) the power of `async` in Python comes into play because it allows something else to happen while your code is just waiting around for a response.

> I tried increasing the number of workers and it really solved the problem I mentioned above.

As I mentioned earlier, this will solve the problem, *to an extent*. It is more of a band-aid solution, especially during development. Perhaps if you are only expecting a handful of connections then this could also work in production. But, if there will be any amount of potential traffic, then you will experience the same problem as outlined above. I would not recommend this as a solution unless you had a very minimal needs (maybe connecting some sensors together in a smart home).
