### ISSUE TITLE
Question: Does sanic benefit from running behind gunicorn?

### ISSUE THREAD

**Issue by mikepc** [huge-success/sanic#1599]
Given the async nature of sanic, I'm curious if there are any benefits to running as a gunicorn worker as opposed to just running behind a "standard" reverse proxy?

**Comment by ahopkins** [comment]
I tend to think not. There is for sure some speed penalty, and you will see a performance difference since the core of sanic's speed will be lost.

I personally prefer to place it behind nginx and see that as a much more performance option.

https://community.sanicframework.org/t/gunicorn-uwsgi-vs-build-in-http-server/47

**Comment by mikepc** [comment]
I really appreciate the reply! I didn't think it would, and really couldn't
think of any reason it would, but I am way rusty in the python ecosystem
and wanted to find out if I were missing something.  Thanks again!

**Comment by ahopkins** [comment]
With that said, I should mention that gunicorn does offer some great features around managing and restarting workers. So, there may be some features that you will not get with the Sanic server. Also, we are closing in on ASGI support which would add another server deployment option. See #1475
