### ISSUE TITLE
pip3 install fails on version 19.6.2 on Mac

### ISSUE THREAD

**Issue by greatvovan** [huge-success/sanic#1643]
When trying to install the package globally:
`pip3 install sanic`
It says in the end:
```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/LICENSE.md'
Consider using the `--user` option or check the permissions.
```
It is expected that access to this directory requires root permissions but it is not clear why setup process tries to write there.

Same works if I specify the previous version 19.6.0.

 - OS: macOS 10.14.5
 - Python3 installed through `brew`

**Comment by madelyneriksen** [comment]
Hi!

You're trying to install Sanic using your user's "global" install of Python that you installed with `brew`. This won't work because, like the error message says, it tries to install into an area that requires elevated permissions.

This is best fixed one of two ways:
* Using a virtual environment with a tool like `venv`, `virtualenv`, or `pipenv`
* OR using the `--user` flag, which will install it locally for your user.

If you're new to Python, you should definitely consider using a virtual environment. It keeps your dependencies isolated so you can work on multiple projects without conflict!

Here is a link to using `venv` [in the python docs](https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments).

**Comment by Tronic** [comment]
MacOS brew normally installs in /usr/local/ where the normal user has write permissions. Perhaps pip3 install sanic should be installing to /usr/local/ rather than /usr/?

@greatvovan Which python3/pip3 are being used on your system? Use which pip3 or which python3 to find out. Are these in /usr/local/bin or /usr/bin?

**Comment by sjsadowski** [comment]
While this is dupable, there are other things that fail using pip/pip3 due to permissions, and not just on MacOS. I wouldn't really call this a sanic issue, and I would endorse using the ```--user``` flag.

Alternately, you can force install it globally with ```sudo pip3 install sanic``` - but I really wouldn't recommend that.
