### ISSUE TITLE
Automatic worker restart

### ISSUE THREAD

**Issue by Sayed-Soroush-Hashemi** [huge-success/sanic#1685]
**The problem**
When a worker dies due to an unexpected reason the master process doesn't restart it.

**My suggested solution**
Adding a signal handler to workers to start a new one (with proper parent process) in case of receiving termination signals.

**Additional context**
I believe it can be added in `sanic/server.py` in function `serve_multiple`

**Comment by Tronic** [comment]
Automatic restarting is handled in the Trio branch that I am testing on (but the whole branch is very experimental and not suitable for real use at this time). The main process always keeps the configured number of workers alive and frequently polls for any dead ones, and will also restart all of them when it receives SIGHUP. The whole multiworker fork logic should probably be restructured for other reasons as well (Windows compatibility/signal handling, and not pickling the app object). That would also allow completely graceful restarts when source code is modified, etc. See #1662 and #1684 for more information.

If you are willing to fix it yourself, feel free to do a pull request. Otherwise it'll take a few months at least until it gets fixed. You'll probably want to keep all restarting/shutdown logic in the parent process that otherwise doesn't really do much, and just have the workers terminate on (any) signals. All help is highly appreciated here.

**Comment by Sayed-Soroush-Hashemi** [comment]
Thanks for the detailed response @Tronic 

We are using Sanic in some sensitive microservices and can't afford to test experimental codes. We managed to go around the problem by tailoring some features of Kubernetes and increasing the resources for those microservices. Even though this problem is still bothering us from time to time, it's not doing so much harm to be given priority. So, I guess we'll wait. But we might decide to contribute in the future if the situation changes.

By the way, the Gunicorn mode has this functionality, but we failed to run it with ASGI. Did we make a mistake or it's not being supported anymore?
