### ISSUE TITLE
Support Oracle??? 

### ISSUE THREAD

**Issue by hanzhenbjm** [huge-success/sanic#1695]
Does the current version support oracle?

**Comment by Tronic** [comment]
If you mean the Oracle database -- Sanic is a web framework and as such has nothing to do with databases. You can use SQLAlchemy or cx_Oracle for talking with the database in the same way you would in any other framework (other than Django that has its own ORM).

Because those libraries aren't async (and I am not aware of any mature async alternatives for them), you won't get the extremely high performance that Sanic would offer with purely async webapps. A higher number of Sanic workers is recommended to keep things running fast.

**Comment by hanzhenbjm** [comment]
those libraries aren't async     so  we can not use it (cx_oracle),    no  otrher libraries  support async  ?

**Comment by sjsadowski** [comment]
Just because something is not async doesn't mean you can't use them in conjunction with something that is; it simply means you will have blocking calls and won't get the benefits of async calls.

Your best bet is to find an async ORM framework like Pony.  You can find these things easily by using a modern search engine.

**Comment by hanzhenbjm** [comment]
our framework  is Sanic ,  but querying the database is slow
