### ISSUE TITLE
SanicTestClient throws error with response.text(...)

### ISSUE THREAD

**Issue by wochinge** [huge-success/sanic#1703]
**Describe the bug**
When an endpoint does not return a json und we are using the `SanicTestClient`, it gives an error:
```
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)]
```

This is because `sanic.testing` import `JSONDecodeError` from `json`, but `requests` (used by `requests_async`) uses `simplejson`, which means that this

```python
 try:
    response.json = response.json()
except (JSONDecodeError, UnicodeDecodeError):
    response.json = None
```

does not work cause it does not handle the actual type `simplejson.errors.JSONDecodeError`

**Code snippet**

Endpoint:
```python
@blueprint.route("/")
async def do_something(request: Request) -> HTTPResponse:
    return response.text("", 200)
```

Request:
```python
test_client = app.test_client
_ = test_client.get("/")
```

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - OS: MacOS
 - Version: 19.6.3

**Additional context**

**Comment by wochinge** [comment]
A simple quickfix would be to import `JSONDecodeError` from simplejson, I can submit a PR for that if you want.

**Comment by wochinge** [comment]
Hi @harshanarayana What speaks against using the `test_client` which is described here https://sanic.readthedocs.io/en/latest/sanic/testing.html ?

**Comment by fabschn** [comment]
Trying to revive the discussion since I am currently facing the same issue. 

I'm not explicitly calling `response.text()` but using the `abort()` function from `sanic.exceptions`.

I this case, the proposed solution of importing the JSONDecodeError from simplejson  (`from simplejson import JSONDecodeError`) in `sanic.testing` leads to the expected behavior. 

@wochinge Did you solve the issue in some way?
Also interested in arguments against using the `test_client` described in the documentation.
