### ISSUE TITLE
The number of machine processes shows a problem

### ISSUE THREAD

**Issue by fengzifrank** [huge-success/sanic#1718]
Hello, I specified worker=12 at startup, but when I checked the number of processes in the machine, I found that 17 I don’t know why there are 5 other processes. My cpu number is 8 The program is all right. Just this is confused.

**Comment by sjsadowski** [comment]
Can you paste a code snippet of what you're doing so I can attempt to duplicate?

**Comment by Tronic** [comment]
Possibly unterminated processes left over from previous run? The child process killing code is not very reliable and will inevitably fail if the main process is killed so it won't have any chance to kill its children.

@fengzifrank Could you verify what happens if you first terminate/kill all Sanic processes and then try to run 12 workers? You should get 12 workers, one host and possibly one autoreloader, for a total of up to 14 processes. 17 shouldn't be possible.

Which OS are you using? Subprocess killing varies substantially among platforms.

**Comment by sjsadowski** [comment]
No response from requestor, closing.
