### ISSUE TITLE
Changes to Blueprints application breaks multiply applied routes!!!

### ISSUE THREAD

**Issue by autumnjolitz** [huge-success/sanic#1742]
Consider the following pattern:

```
@app.get("/url1")
@app.get("/url2")
async def handle_multiple(request):
     return text("some response")
```

The recent change in #1690 breaks that pattern.

It's a common pattern to use multiple `@blueprint.get(...)` and `@app.get(...)` to handle routes that have common behavior with slight variations, like a login process.

The only alternative I can think of is splitting out each of these routes into distinct rump functions that literally forward onto a common function, which inflates from one line declarations to three lines plus the constant common route handler.

**Comment by harshanarayana** [comment]
@benjolitz

The original change in #1690 was done in order to account for an old standing open issue that actually needed fixing. I missed this case when implementing the change that seems to have broken the case of multiple routes being bound to the same handler method. 

Let me see what can be done to address this while still being able to handle the original request from #37

**Comment by autumnjolitz** [comment]
@harshanarayana okay. wrong username for me btw. ;)

**Comment by harshanarayana** [comment]
@autumnjolitz oh. Sorry. That explains why the auto complete wasn't working last night. 😂 sorry about the mistake

**Comment by ashleysommer** [comment]
Hi @autumnjolitz 
Until we get a proper fix for this, can you try this workaround?

```
async def handle_multiple(request):
     return text("some response")
names1, handler1 = app.get("url1")(handle_multiple)
names2, handler2 = app.get("url1")(handle_multiple)
```

**Comment by autumnjolitz** [comment]
Thank you @ashleysommer !
