### ISSUE TITLE
Response XML

### ISSUE THREAD

**Issue by johndiego** [huge-success/sanic#1744]
from sanic.response import json,text,html,raw

this is possible xml too?

**Comment by chenjr0719** [comment]
Hi there

For now, if you want to respond with XML, please using text and set the content type to `text/xml` directly. Here is an example:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic()


@app.get("")
async def test(request):
    content = """
    <note>
        <to>Tove</to>
        <from>Jani</from>
        <heading>Reminder</heading>
        <body>Don't forget me this weekend!</body>
    </note>
    """

    return text(content, content_type="text/xml")


if __name__ == "__main__":
    app.run(debug=True)

```

And if you really want to add an `xml()`  method in `sanic.response`, you can try to send a PR for it.

**Comment by Tronic** [comment]
Depending in on usage `application/xml` or a more specific type `application/xml+something` would be more appropriate than the text type. The purpose of `text/xml` is to display it as plain text if the client cannot handle XML, and that is seldom useful to any degree. Since there is no single universal XML mime type and format, it doesn't make much sense for Sanic to have such response type (there is no standard way of representing e.g. Python dict in XML, like you do with JSON responses).

**Comment by ahopkins** [comment]
Agreed. I do not see this as a huge need. Perhaps if it is more convenient for you, you can create one yourself:

```python
from sanic.response import HTTPResponse

def xml(
    body, status=200, headers=None, content_type="application/xml; charset=utf-8"
):
    return HTTPResponse(
        body, status=status, headers=headers, content_type=content_type
    )
```

**Comment by Tronic** [comment]
Minor note: charset is only used on text MIME types. XML is UTF-8 unless a different encoding is specified within the document itself. At least regarding standards; your implementations may vary.
