### ISSUE TITLE
Any plans to support Ctrl+C on Windows?

### ISSUE THREAD

**Issue by danieldaeschle** [huge-success/sanic#1753]

**Comment by ahopkins** [comment]
I will be the first to admit that I am not aware of what would be involved to add this signal. 😬

Any one that is more versed in Windows want to chime in?

**Comment by ahopkins** [comment]
With a couple minutes of Google.... https://stackoverflow.com/a/52941752

**Comment by danieldaeschle** [comment]
Using windows api like in the example looks like a nice solution.

**Comment by ahopkins** [comment]
@danieldaeschle does `CTRL-Break` work?

**Comment by danieldaeschle** [comment]
I have to test it.

Adam Hopkins <notifications@github.com> schrieb am Do., 9. Jan. 2020, 19:17:

**Comment by seemethere** [comment]
I don't really feel like adding this functionality into `sanic` core would be greatly beneficial when there are already widely known alternatives.

Especially when the `code` solution to this is adding in a special case just for windows.

**Comment by Tronic** [comment]
I had planned to fix this but recently I don't have much time to work on Sanic at all. The problem might be that of terminating the worker processes, so it might already be resolved if you don't use workers or autoreload, and if that is the case, the thing needing implementation is better killing logic (because Windows doesn't have proper signals), e.g. closing child process stdin from parent.

**Comment by danieldaeschle** [comment]
@ahopkins I just tested Ctrl+Break. I doesn't work. Neither with 4 workers, nor with one worker.
