### ISSUE TITLE
Avoid runtime dependency on httpx unless testing is used

### ISSUE THREAD

**Issue by Tronic** [huge-success/sanic#1826]
Sanic only depends on httpx for testing but that actually becomes a hard dependency because `sanic/__init__.py` imports `sanic.app` which imports `sanic.testing` that then imports `httpx`. This is a problem because HTTPX frequently makes incompatible API changes and packages other than Sanic also depend on specific versions of it being installed.

On Sanic master branch one cannot even `import sanic` if there is httpx<0.10 or httpx>=0.12 installed, in contrast with Sanic 19.12LTS where one must have httpx<0.10.

Code could be restructured so that sanic.testing is only imported when needed. Possibly this means importing it inside `app.test_client` and `app.asgi_client` functions.

A related question is whether testing should be moved to a separate package or to `pytest-sanic`, to avoid installation of `httpx` by the main package. `pip install` won't refuse installs when there are conflicting requirements but wrong versions may end up installed.

Another alternative would be to use some other HTTP client in testing, one that has a more stable API and ideally one that would be fully asynchronous (https://github.com/encode/httpx/issues/877).

Or if all of that seems too problematic, we could just do nothing and keep things the way they are, and try to keep up with httpx development. Care to share your thoughts?

**Comment by tnachen** [comment]
Also love to see httpx removed as a requirement, especially if it's only used in testing.

**Comment by ahopkins** [comment]
The main problem is there is sort of a lack of decent http clients that can reach inside an ASGI compatible application and execute it without standing up the server. `httpx` follows on the heals of `requests-async`.

That being said, yes, I agree that it is annoying. I am in favor of doing something like this especially so that production builds can be as lean as possible.

I think this conversation does not stop with `httpx`, but should also include `aiofiles` and `websockets`.

Seeing as we already have one method for removing some dependencies at install time (`SANIC_NO_UJSON and `SANIC_NO_UVLOOP`), perhaps we go with a similar method. This could get messy.

The alternative would be to have various requirements relegated to extras:

`$ pip install sanic[test,websockets]`

To achieve this, we would probably need to add a constructor to `Sanic` to add those properties at runtime only if `httpx` was installed.

**Comment by Tronic** [comment]
Agreed, httpx looks like the most feasible choice.

> To achieve this, we would probably need to add a constructor to Sanic to add those properties at runtime only if httpx was installed.

Probably rather add functions to the **class** when the Sanic module is imported. But wouldn't simple `import` statements inside `test_client` and `asgi_client` methods do? That shouldn't be too difficult to implement, and would not affect API docs and tools like dynamically creating these methods might.

> The alternative would be to have various requirements relegated to extras:
>
> `$ pip install sanic[test,websockets]`

I'm not a big fan of `SANIC_NO_SOMETHING=YES` install options; `sanic[...]` seems more reasonable.

**Comment by ashleysommer** [comment]
During the Steering-Council meeting yesterday, we concluded a good idea would be to split out the `sanic/testing.py` code into a standalone package (`sanic_testing`?) and _that_ will have the `httpx` dependency.

Then `sanic` can include `sanic_testing` as a dev_dependency or tests_dependency.

**Comment by ahopkins** [comment]
Closing in favor of #1850.

**Comment by ahopkins** [comment]
@ashleysommer I pushed the repo before seeing your message. I like `sanic_testing` better to stay consistent with the existing module. With my next push I will rename it.

**Comment by ahopkins** [comment]
Conversation continued: https://community.sanicframework.org/t/sanic-testing-and-dependency-on-httpx/556
