### ISSUE TITLE
py3.8 is missing from package badge

### ISSUE THREAD

**Issue by DavidBord** [huge-success/sanic#1830]
I think because 3.8 is missing in pypi "Classifiers"->"Programming Language"

**Comment by Tronic** [comment]
Python 3.8 is listed in setup.py of Sanic master branch, so I guess that'll get fixed on next release.

**Comment by ahopkins** [comment]
This had been intentional at the time of the last release since we had not at the time properly tested against Python 3.8. In fact, there had been some issues with some upstream packages. It should be okay going forward and will be added.

Now... if anyone wants to start testing against 3.9, that would be great.

**Comment by DavidBord** [comment]
I'll try:
- One CI step name was incorrect (PR already merged).
- The failing tests fail on a breaking change in py3.9. I opened an issue on websockets: https://github.com/aaugustin/websockets/issues/760

**Comment by DavidBord** [comment]
Tried to fix websockets code and found out everything is up to date there.
I am doing way to much mess for an already closed issue :)
Moved it to #1856
