### ISSUE TITLE
chardet version bump

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [huge-success/sanic#1858]
Do you really need that old chardet version?

**Comment by ahopkins** [comment]
What version of `sanic` are you using?

A couple things on that:

1. `chardet` is an upstream dependency [from `httpx`](https://github.com/encode/httpx/blob/master/setup.py#L61), we do not control that
1. It looks like `httpx` is requesting the latest version [according to pypi[(https://pypi.org/project/chardet/)
1. We are in the process of [removing `httpx` as a dependency](https://github.com/huge-success/sanic/pull/1850) since it is really only used in testing

**Comment by ashleysommer** [comment]
@Alessandro-Barbieri 
Is this question resolved for you?

**Comment by Alessandro-Barbieri** [comment]
Can you remove dependency not strictly required, why do you need the deps dependencies? This will make manual packaging more easy

**Comment by ahopkins** [comment]
Did you read the links? If yes, I'm not sure I understand the question.

**Comment by Alessandro-Barbieri** [comment]
> @Alessandro-Barbieri
> Is this question resolved for you?

Now that I know, I'll just remove the chardet dependency from the package. I think it's better to leave this issue open until it's really removed or it's version bumped.

**Comment by Alessandro-Barbieri** [comment]
I was suggesting in removing all the requirements that are dependency of the dependencies since you'll get them installed anyway with a decent package manager

**Comment by ahopkins** [comment]
It is not. Where are you looking?

```
requirements = [
    "httptools>=0.0.10",
    uvloop,
    ujson,
    "aiofiles>=0.3.0",
    "websockets>=7.0,<9.0",
    "multidict>=4.0,<5.0",
    "httpx==0.11.1",
]
```

From setup.py

**Comment by Alessandro-Barbieri** [comment]
tox.ini
https://github.com/huge-success/sanic/blob/bedf68a9b2025618a94cb8044f495a0abd87a134/tox.ini#L17

Il Sab 13 Giu 2020, 20:47 Adam Hopkins <notifications@github.com> ha
scritto:

**Comment by Tronic** [comment]
Fix just merged upstream in httpx, they no longer use chardet.
