### ISSUE TITLE
get_headers deprecation

### ISSUE THREAD

**Issue by ahopkins** [huge-success/sanic#1860]
@Tronic 

In [commit bffdb3b](https://github.com/huge-success/sanic/commit/bffdb3b5c243f7fc2b534ea6bf3e91a40725a641), you added [`BaseHTTPResponse.get_headers`](https://github.com/huge-success/sanic/blob/master/sanic/response.py#L44) and a note.

> .. deprecated:: 20.3:
> This function is not public API and will be removed.

What is the plan for removing it, and then what will we replace it with? I have a PR that I want to make to the Headers and I am not sure what the intent is with this notice.

**Comment by Tronic** [comment]
The intent is to move all protocol-specific parts away from response objects, namely to `http.py` of the streaming branch, and to ASGI servers. This function can only be used for HTTP/1 responses with the built-in server because it returns a bunch of bytes. Adding `Content-Type` belongs to response objects but HTTP version, keep-alive and `Connection` headers are protocol implementation details that cannot be properly handled here.

**Comment by ahopkins** [comment]
OK. I'm going to make my PR and change the notation. Thanks.
