### ISSUE TITLE
Why does Sanic server runs twice?

### ISSUE THREAD

**Issue by azizullah2017** [huge-success/sanic#1862]
**Describe the bug**
Sanic code runs twice 

**Code snippet**
```
app.static('static', 'static')
jinja = SanicJinja2(app)
print ("======test statement========")


@app.route('/')
def index(request):
	return jinja.render("index.html", request)


if __name__ == '__main__':
	app.run(host='0.0.0.0',port=5002)
```

python3 test.py 
======test statement========
======test statement========
[2020-05-22 16:42:49 +0500] [1449] [INFO] Goin' Fast @ http://0.0.0.0:5002
[2020-05-22 16:42:49 +0500] [1449] [INFO] Starting worker [1449]

**Expected behavior**
======test statement========
[2020-05-22 16:42:49 +0500] [1449] [INFO] Goin' Fast @ http://0.0.0.0:5002
[2020-05-22 16:42:49 +0500] [1449] [INFO] Starting worker [1449]

**Comment by Tronic** [comment]
With multiple workers running the module twice is often unavoidable. However, I believe that this should not happen on UNIX (where fork is used for multiple processes), and also not when `workers=1`. Anyone care to debug why this happens?

**Comment by myuz** [comment]
@Tronic I've tried to reproduce it on the UNIX, everything works fine.

@azizullah2017 which OS you're using? did you try to set `workers=1`?

**Comment by Tronic** [comment]
Autoreloader might be another culprit because it also spawns an extra process.

**Comment by ashleysommer** [comment]
@Tronic 
I believe that is correct. When I run with auto_reloader on I see the startup message twice.

Autoreloader also messes with my pycharm debugging process, so I usually disable it when starting work on a new application.

**Comment by azizullah2017** [comment]
@Tronic I have tried with ```worker=1``` still having the same behavior.
@myuz I am using ```Ubuntu 18.04 and sanic Version: 19.3.1```

**Comment by ahopkins** [comment]
I am looking into this. It seems to be specifically related to `auto_reload=True`.

**Comment by ahopkins** [comment]
So, I am not entirely sure there is much we need to do here. This is because of this line:

https://github.com/huge-success/sanic/blob/7c04c9a22775ffbff04dc17ad4d605591a6ae20e/sanic/reloader_helpers.py#L142

When you have `workers=1` and `auto_reload` turned on, the main process will run the watchdog, and it will kickoff a background process to handle the worker.

Now, I am not 100% worried about that. Assuming that you are using listeners properly and not executing code in your global scope, nothing would be executed twice. Indeed, nothing is actually being executed twice. At least not in the same process.

Those logs appear because it is once in the worker, and once in the watchdog process. The watchdog doesn't run your application, and is for development purpose only. 

I am inclined to leave this as is, and mark this closed. Convince me otherwise.

**Comment by chapati** [comment]
> I am inclined to leave this as is, and mark this closed. Convince me otherwise.

Server initialization can be quite heavy, like reading env, verifying configuration, testing availability of services &c. Doing it twice doubles amount of time and waiting which is especially annoying in dev environments. I've been considering using sanic instead of fastapi for one of the projects but this issue is a huge no-no unfortunately. FastAPI + uvicorn do not do that.
