### ISSUE TITLE
REAL_IP_HEADER config does not work

### ISSUE THREAD

**Issue by koug44** [huge-success/sanic#1863]
**Describe the bug**
REAL_IP_HEADER config does not work or at least setting it does not change the value of request.ip

**Code snippet**
Code adapted from the _Hello World_ example of the documentation

```
from sanic import Sanic
from sanic.response import json

app = Sanic("hello_example")


@app.route("/")
async def test(request):
    return json(
        {
            "Header": request.headers.get("X-Real-IP", "Not found"),
            "Request IP": request.ip,
        }
    )


if __name__ == "__main__":
    app.config["REAL_IP_HEADER"] = "X-Real-IP"
    app.run(host="0.0.0.0", port=8000)
```

**Expected behavior**
With these request 
`http "http://localhost:8000" "X-Real-IP:8.8.8.8"`

I would like request.ip to be 8.8.8.8

**Environment (please complete the following information):**
 - Python is 3.8.3
 - Sanic is 19.12.2

**Comment by syfluqs** [comment]
according to the logic in current source, `request.ip` is set from the immediate ip from the request and not from the proxy forward headers. you can find the x-real-ip value in `request.forwarded.get('for')`

**Comment by koug44** [comment]
Looking at the source, I've also find the X-Real-IP value in `request.forward_addr`

But if request.ip is always the immediate IP, I don't see the point of the REAL_IP_HEADER config.

My main issue is that I would like the real IP address to be in the access.log, and it's currently request.ip that is being used

**Comment by syfluqs** [comment]
I think you meant the `request.remote_addr` property. As far as my knowledge goes, reverse proxies like nginx replace the requests source ip value with its own and instead put the original ip in the `X-Real-Ip` header. This way the webserver can differentiate between two requests, one which it received directly and one which it received through the reverse proxy on the basis of the presence of the `X-Real-Ip` header.

Now to your problem, if you want to change the value in the access logs and don't mind a little monkey patching, you can modify the `log_response` method in `server.py` before you initialize your app. In that method various fields from the request are picked and put in an `extra` dict which is then passed to the `access_logger`. You would need to change the access log formatter as well, if you add the real ip to a key other than `host`.

**Comment by syfluqs** [comment]
You can also use a request middleware
```python
@app.middleware('request')
async def print_real_ip(request):
    your_logger.info(f'X-Real-Ip: {request.remote_addr}')
    # ... or perhaps you want to change the request.ip value altogether, though I would suggest against this
    request._socket = (request.forwarded.get('for'), request.forwarded.get('port'))
```

**Comment by koug44** [comment]
Thanks for the ideas. I guess I can find a «monkey-patch» way

But still, if I need to override methods, the REAL_IP_HEADER has no value. It's the reason why I opened this as an issue in the first place: I can always get the real IP through 'request.headers' but I think the whole idea of having a global config like REAL_IP_HEADER is to make it seamless.

And moreover, as I guess a majority of users are using Sanic behind a reverse proxy, I don't get why it would be so complicated to have the requester IP address in the access.log (which is one of the basic information)

**Comment by syfluqs** [comment]
As I see it, the header value should only be trusted by the application developer if its origin is known i.e. they know that they have placed a reverse proxy in between which is providing that value. Since there is no other way to verify its authenticity the header value can very easily be altered (for example by a man in the middle). For all other cases apart from a trusted reverse proxy, the header should be ignored, which is why it is necessary for the webserver to differentiate the forwarded ip and the actual ip it received from the TCP/IP packets source address field.

**Comment by Tronic** [comment]
The remote address is found in `request.remote_addr` because `request.ip` is always the peer address *directly* connecting to Sanic.

I'd recommend switching to the standard `Forwarded` header by following the Nginx deployment docs where X-headers are not used: https://sanic.readthedocs.io/en/latest/sanic/nginx.html

If you wish to keep using the traditional X-prefixed headers, remember to set the proxy count as well:

```python
app.config.PROXIES_COUNT = 1
app.config.REAL_IP_HEADER = "X-Real-IP"
```

This is documented in https://sanic.readthedocs.io/en/latest/sanic/config.html#traditional-proxy-headers

**Comment by ahopkins** [comment]
Feel free to continue the conversation if needed.
