### ISSUE TITLE
Run Sanic on http, https, unix socket simultaneously.

### ISSUE THREAD

**Issue by tomaszdrozdz** [huge-success/sanic#1896]
Is there a way to run Sanic on http, https, unix socket at the same time ?

For example:

    app.run(host="0.0.0.0", port="8000")

Then it runs on http
but

    app.run(host="0.0.0.0", port="8000", ssl={...})

Then it runs only on https.

**Comment by Tronic** [comment]
No, but you can run multiple instances for any addresses/sockets with/without SSL that you may need. Pull requests are welcome, I guess, but this is not likely to be implemented by us any time soon because binding multiple interfaces within the same process is not that important (multiple workers within one Sanic server are supported only because otherwise they couldn't easily bind to same listening address).

**Comment by ahopkins** [comment]
I agree with @tronic. It is easy enough to run multiple instances to cover different schemes that adding this into the server itself is not a huge win.

I think we probably should add some deeper documentation on deployment strategies. This seems to be on of the most common questions that we get.

**Comment by tomaszdrozdz** [comment]
OK :)
