### ISSUE TITLE
auto_reload not supported by create_server method

### ISSUE THREAD

**Issue by rgeronimi** [huge-success/sanic#1925]
**Describe the bug**
The documentation states that an app's `create_server` method is the async equivalent of its `run` method.
However the `create_server` method does not support the `auto_reload` argument that is correctly supported
by the `run` method.

**Environment (please complete the following information):**
 - OS: MacOS 10.15.6
- Python: 3.7.8
- sanic: 20.6.3

**Comment by myusko** [comment]
Yes, you're right! currently, the `create_server` method, doesn't support the `auto_reload` option, we should investigate whether it is technically possible to add the argument.

@ahopkins technically it's possible to implement, isn't it?

**Comment by Tronic** [comment]
It doesn't make so much sense to use autoreloader in async mode because multiple processes are needed for that to work. The main process keeps monitoring source code files and it runs the actual server as a child process, which in case of multiple workers runs its own children to serve requests. When source files are modified, the server process gets terminated and restarted.

In other words, whenever you use `auto_reload` or `workers > 1`, requests are no longer served in your main loop, and having some tiny fragment of Sanic run within that loop is not really helpful.

The `create_server` method is a low level entry point that should only be used when you wish to implement process management yourself (mostly useful for developers of platforms like *unicorn, I guess). Normal users should use the `run` method, the `sanic` script or the ASGI API.

**Comment by rgeronimi** [comment]
I wasn't aware that files monitoring required multiple processes. In such case I agree it makes sense to not implement the autoreloader flag.

**Comment by ahopkins** [comment]
Thanks @Tronic for the nice writeup here. The `create_server` option for running (as mentioned) is not the recommended usage, except in certain edge cases.
