### ISSUE TITLE
Support middleware exception handlers

### ISSUE THREAD

**Issue by vishalkuo** [huge-success/sanic#1928]
**Is your feature request related to a problem? Please describe.**
Some of our middleware currently throw transient exceptions, especially at startup. The current behavior of the middleware layer is to [log the exception](https://github.com/huge-success/sanic/blob/master/sanic/app.py#L984-L988) no matter what. 

**Describe the solution you'd like**
Ideally we'd be able to create our own exception handler, similar to the sanic `ErrorHandler` that is capable of dealing with these. Alternatively, it'd be nice if we can just pipe exceptions from the middleware to the web error handler too.

I'm happy to help out with these changes, if that'd be useful

**Comment by ashleysommer** [comment]
Hi @vishalkuo 
Looks like you are talking about _Response Middleware_ specifically.
It is already possible to do what you are asking, with _Request Middleware_, see the [Handling Exceptions section](https://sanic.readthedocs.io/en/latest/sanic/exceptions.html#handling-exceptions) of our documentation for details.

The line you linked to applies only to _Response Middleware_, where an exception from a response middleware will be logged, but not passed to the error handler.
That is because an Exception handler's job is to generate a HTTP response from the exception. But Response Middlewares only run _after_ a normal response has been generated. So it doesn't make sense to pass the exception to a handler at that stage. It was also a decision by the early developers of Sanic to transparently log these exceptions from Response middlewares and not raise them, so that a broken response middleware cannot prevent the HTTP Response from being sent.

I hope that clears it up.
If I've misunderstood your question, please clarify what it is you are asking.

**Comment by vishalkuo** [comment]
Thanks for the prompt response, @ashleysommer. I guess what I'm really asking for here is a way to explicitly control how we handle the exception thrown in a response middleware. A couple ways would be

- Provide a callback specific to the response middleware that we can use that is independent of the request and doesn't modify anything like return code
- Provide a flag to let us control logging here (less ideal since we'd still want to be able to log these with different clients like statsd)  

Let me know if that doesn't make sense

**Comment by ashleysommer** [comment]
Hi @vishalkuo 

See this example for how you can implement that yourself with a middleware wrapper:
```python3
from functools import wraps
from sanic import Sanic
from sanic import response

app = Sanic(__name__)

class MyException(Exception):
    pass

def my_exception_handler(ex):
    # Do exception handling here.
    if isinstance(ex, MyException):
        #handle my exception
        print(ex)
    else:
        print(ex)

def my_response_middleware(f):
    def mw(request, response):
        try:
            return f(request, response)
        except Exception as ex:
            return my_exception_handler(ex)
    mw = wraps(f)(mw)
    app.middleware('response')(mw)
    return mw

@my_response_middleware
def middleware1(request, response):
    a = request.invalid  # raises attr error
    return

@app.route("/")
async def test(request):
    return response.json({"test": True})


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000, debug=True, auto_reload=False)
```

**Comment by ashleysommer** [comment]
@vishalkuo
Does the above code example answer your question?

**Comment by vishalkuo** [comment]
Apologies, yes, it does. Thanks
