### ISSUE TITLE
Request factory to facilitate unit testing

### ISSUE THREAD

**Issue by vomindoraan** [huge-success/sanic#799]
Hello,

The way we currently do endpoint testing is through `SanicTestClient`, which runs a Sanic instance, opens a session, performs the test and returns the results. However, for unit tests it would be nice if we could bypass the protocol and handle the instantiation of the request objects ourselves, so that we have full control over the input and output of the routes being tested.

This could be done with a [RequestFactory](https://docs.djangoproject.com/en/1.11/topics/testing/advanced/), like in Django.

**Comment by jrocketfingers** [comment]
I'd like to add that this allows us to capture exceptions within the unittests. This is super handy if you use pytest, as it gives you a breakdown of asserted values, colors the stack trace in case of exceptions, etc.

The problem is in the fact that the sanic server captures the exception so it could format a 500 response. Since Sanic isn't really the SUT in your average unittest, this would allow you to skip it.

Any tips on what should we keep in mind if we get down to work on a request factory?
