### ISSUE TITLE
sanic behind proxy - option to replace IP of request.ip with X-Forwarded-For value

### ISSUE THREAD

**Issue by intra-au** [huge-success/sanic#801]
Dear Devs,
Please consider adding an option to replace request.ip with X-Forwarded-For value, it will make life a lot easier for those of us who running sanic behind nginx or load balancer.

I can get real IP with request.headers.get('X-Forwarded-For') but would be good to have an option to set custom header for sanic to get ip address from so it can get added in sanic logs, console etc.
It's quite common and as an example Flask has ProxyFix to address this.

**Comment by andreymal** [comment]
#853 looks unconfigurable and unsafe, something like [werkzeug ProxyFix](https://github.com/pallets/werkzeug/blob/64d1d2117cc177b9caf18bb571f32133492978c3/werkzeug/contrib/fixers.py#L97) would be better

**Comment by andreymal** [comment]
...but this is still unsafe :/

**Comment by sjsadowski** [comment]
Perhaps, but the original need was addressed, reviewed, and merged. @andreymal perhaps you can submit a new PR to address your concerns?

**Comment by untitaker** [comment]
BTW, the default configuration in Sanic is still completely unsafe.

https://github.com/huge-success/sanic/blob/891f99d71d3bd17501a9762b0843736f4377e3f3/sanic/request.py#L358-L362

The docstring is misleading in the sense that it implies Sanic has the necessary knowledge to decide whether a header can be trusted or not, but per default it just trusts any header that comes its way.

>Perhaps, but the original need was addressed, reviewed, and merged.

BTW, this mindset of "let's just address one need at a time and don't think about security implications" is exactly why IP-based limits in strawpoll can still be bypassed by sending X-Forwarded-For.

**Comment by andreymal** [comment]
>Sanic has the necessary knowledge

Yes, it has. See `PROXIES_COUNT` and `REAL_IP_HEADER` options ([#1539](https://github.com/huge-success/sanic/pull/1539))

**Comment by untitaker** [comment]
@andreymal sanic has the necessary knowledge if somebody took time to configure those values. Per default sanic just trusts `x-forwarded-for` and `x-real-ip` as far as I can tell.

**Comment by untitaker** [comment]
In any case, I can see why you would want to have this as a default, I am just saying that this needs to be made very explicit as it works unlike most other Python web frameworks I've seen, where reading from proxy headers is usually opt-in (Flask, Django at least).

Consider that strawpoll's IP-based voting limits can still be circumvented by setting proxy headers because of this kind of default in whatever framework they use. I guess whether this is important really depends on what you use the IP for.

**Comment by Tronic** [comment]
I am currently working on this in #1636. Having so many unsafe proxy headers being trusted by default is definitely problematic because any one of them may go unfiltered by the proxy and happily accepted by Sanic. It is worth noting that X-Scheme, X-Forwarded-Proto, X-Forwarded-Port and X-Forwarded-Host are trusted irregardless of Sanic config variables that may be used to secure or disable X-Forwarded-For and X-Real-IP.

To be frank, I believe it would be best to disable all these headers by default, and quite possibly to entirely drop support for many of them in favour of using the new Forward header (for which I currently require config.FORWARDED_SECRET to be defined).

**Comment by untitaker** [comment]
Strongly agreed, current state is irresponsible.
