### ISSUE TITLE
vhost with https

### ISSUE THREAD

**Issue by blark** [huge-success/sanic#860]
Hi there, the vhosts example is great, I was wondering if there is a way to do vhosts with ssl? If so is there any chance you could maybe add that to the example, as I'm a bit confused on how to properly specify certificates for each vhost. Thanks!

**Comment by r0fls** [comment]
I think this is not currently possible.

**Comment by blark** [comment]
Good to know, I figured as such. 

A little background/justification for this. Sanic is fast enough for my needs as a small web server. I am looking to set up several vhosts with TLS using it without any other crap or stuff to set up like Apache or Nginx, etc. It would be really awesome to be able to do this all with just Python...

**Comment by icnahom** [comment]
This would be a nice feature to have.

**Comment by ahopkins** [comment]
I have not tried this.... but I think it should be possible.

```python
from sanic import Blueprint, Sanic

shared = Blueprint("Shared")

HTTPS_PORT = 443

host1 = Sanic("Host1")
host2 = Sanic("Host2")

host1.config.SERVER_NAME = "example1.com"
host2.config.SERVER_NAME = "example2.com"

ssl1 = {"cert": "/path/to/cert1", "key": "/path/to/keyfile1"}
ssl2 = {"cert": "/path/to/cert2", "key": "/path/to/keyfile2"}


@shared.get("/", host=host1.config.SERVER_NAME)
def host1_endpoint(request, path):
    ...


@shared.get("/", host=host2.config.SERVER_NAME)
def host2_endpoint(request, path):
    ...


@host1.before_server_start
async def start(host1, _):
    global host2
    await host2.create_server(
        host=host2.config.SERVER_NAME,
        port=HTTPS_PORT,
        return_asyncio_server=True,
        ssl=ssl2,
        asyncio_server_kwargs={
            "reuse_port": True,
        },
    )
    host2.after_start()


@host1.before_server_stop
async def stop(host1, _):
    global host2
    host2.before_stop()
    await host2.close()
    host2.after_stop()


host1.blueprint(shared)
host2.blueprint(shared)

host1.run(
    host=host1.config.SERVER_NAME,
    port=HTTPS_PORT,
    ssl=ssl1,
)
```

You may need to change `host1.run()` into a create_server pattern to be able to send `reuse_port`. However, it is certainly possible for a single Sanic main process to run multiple Sanic app instances. It is also possible for a single blueprint to be registered to multiple Sanic apps.

**Comment by Tronic** [comment]
Wait what, you just run two separate servers on the same port? No, that won't work. At best you have requests randomly assigned to each which will fail 50 % of requests. On MacOS you get all requests going to one server with the other working as a fallback that never receives anything. (IIRC, didn't verify my sources)

What you actually need for TLS vhosts is an SNI callback on SSLContext, so that you get the vhost being accessed and can react accordingly within a single server (happens right after after TLS client hello packet, before the first server packet where the server would offer certs). https://docs.python.org/3/library/ssl.html#ssl.SSLContext.sni_callback

I think I did this in the Sanic Trio branch but I don't believe the Sanic mainline checks SNI at all.

**Comment by ahopkins** [comment]
That's what I'm not sure about. If it would randomly assign or send to both. If I were to implement, I'd put each server on their own port with a proxy in front. Either way, tls or not the principle should work and you can run multiple instances and bind the same blueprint to them but keep host routing.
