### ISSUE TITLE
Config Type Casting

### ISSUE THREAD

**Issue by gsmcwhirter** [huge-success/sanic#864]
When using environment variables to populate a sanic config, things are currently attempting to type cast to int and then to float and then to leave the value as a string.

This behavior is potentially problematic. All environment variables are represented to python as strings (which is why you were casting in the first place). However, I think it should be up to the user (or at least configurable) to attempt the casts. 

Given the current behavior in the master branch, it is not possible to pass through strings that consist of digits (and possibly decimals) alone. One use case for such as string would be passing in a file permission such as "0755", where sanic would convert this to an int, dropping the leading 0, or passing in something like "+1e0", where that string representation gets lost in favor of the float 1.0 or the string "+1e17203491" becomes `float("inf")`.

I suggest that a better way to maintain the convenience would be to add "get_int", "get_float", etc. casting functions to the Config class, so that people can retrieve the exact environment representation with .get, but also easily retrieve casted items when a certain type is expected/desired.

**Comment by Frzk** [comment]
I kind of agree with your suggestion. I'd even like to take it one step further and propose to use the configparser.ConfigParser object that is available in the standard library (https://docs.python.org/3.3/library/configparser.html)

It has all the needed API (`getboolean`, `getint`, `getfloat`, ...), you can provide fallback values where necessary, it can be initialized with default values and the .ini config file syntax is easy (it doesn't require Python knowledge), yet powerful.

This .ini config file could be loaded from an environment variable, making it easy to switch between different configurations (ie. prod, dev, debug, ...).

I'm volunteering to make the necessary changes if you decide to go this way (in fact I already wrote some code because I wanted to make that proposal for a few weeks).

**Comment by gsmcwhirter** [comment]
I don't have much experience with the built-in ConfigParser, but the behavior I'd suggest maintaining is the .load_from_environment() that the current sanic Config has. It makes things quite nice for working in docker to be able to specify new connection parameters and other config-y bits without rebuilding the image with a new config file inside.

**Comment by yunstanford** [comment]
We don't need a builtin ConfigParse, `yaml.loads` or `json.loads` is enough. 

yeah, load_from_env is convenient. But, For `local development`, you may not need to rebuild a docker image for picking up config-value or modifying code. it'd be better just mount `config dir` or `service dir`.

**Comment by gsmcwhirter** [comment]
I actually do want that. I would like to have a default set in a file and have the env vars override in a programmatic way. Perhaps the sanic config is just not the way to go and I'll override it with custom code.

**Comment by jamesstidard** [comment]
@gsmcwhirter I did actually write a [small extension](https://github.com/jamesstidard/sanic-envconfig) for Sanic to do type casting which might be what you're after.

P.S. I did just stumble on this from skimming my GitHub notifications; I'm not actively out looking for opportunities to plug stuff :p
